server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:test
    username: sys as sysdba
    password: 12345678
    driverClassName: oracle.jdbc.pool.OracleDataSource
  liquibase:
    enabled: true
    change-log: classpath:liquibase/root.xml

